name: Deploy Images to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
      push-store-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: './Store'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build Inventory Image'
            working-directory: .
            run: |
              docker build --platform linux/amd64,linux/arm64 --tag ghcr.io/s3tupw1zard/mega-webdav-docker:latest --push .
              docker build --platform linux/amd64,linux/arm64 --tag ghcr.io/s3tupw1zard/mega-webdav-docker:$(date +'%Y-%m-%d') --push .
